# Generated by Django 6.0.3 on 2026-03-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=512)),
                ('referrer', models.CharField(blank=True, max_length=512)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page'], name='analytics_p_page_a5a095_idx'), models.Index(fields=['created_at'], name='analytics_p_created_4c2b45_idx')],
            },
        ),
    ]
