# Generated by Django 6.0.3 on 2026-03-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistsubmission',
            name='whatsapp',
            field=models.CharField(max_length=30),
        ),
    ]
